name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose --file https://github.com/mhmtonrn/springboot-mongodb-havelsan/blob/master/src/main/resources/docker-compose.yml up -d
